modules-search: [ local ]

instances:
    - id: bootstrap
      module: shellprocess
      config: shellprocess@bootstrap.conf
    - id: install
      module: shellprocess
      config: shellprocess@install.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - shellprocess@bootstrap
      - fstab
      - shellprocess@install
      - bootloader
      - users
      - localecfg
      - networkcfg
      - hwclock
      - mkinitfs
      - umount
  - show:
      - finished

branding: matcha
prompt-install: false
dont-chroot: false
