modules-search: [ local ]

instances:
    - id: bootstrap
      module: shellprocess
      config: shellprocess@bootstrap.conf
    - id: install
      module: shellprocess
      config: shellprocess@install.conf
    - id: cleanup
      module: shellprocess
      config: shellprocess@cleanup.conf

sequence:
  - show:
      - welcome
      - locale
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - shellprocess@bootstrap
      - fstab
      - shellprocess@install
      - bootloader
      - users
      - locale
      - localecfg
      - mkinitfs
      - shellprocess@cleanup
      - umount
  - show:
      - finished

branding: matcha
prompt-install: false
dont-chroot: false
