modules-search: [ local ]

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - packages
      - fstab
      - users
      - localecfg
      - networkcfg
      - hwclock
      - contextualprocess
      - mkinitfs
      - services-openrc
      - bootloader
      - umount
  - show:
      - finished

branding: default
prompt-install: false
dont-chroot: false
