unpack:
    - source: "/"
      sourcefs: "file"
      destination: "/"
      exclude:
          - "/dev"
          - "/proc"
          - "/sys"
          - "/run"
          - "/tmp/*"
          - "/boot/*"
          - "/mnt"
          - "/media"
          - "/sysroot"
          - "/etc/calamares"
          - "/usr/share/calamares"
          - "/usr/lib/calamares"
          - "/usr/bin/calamares"
          - "/etc/polkit-1/rules.d/calamares.rules"
          - "/etc/sudoers.d/matcha"
          - "/root"
          - "/home"
          - "/var/cache/apk"
          - "/var/log"
