efiBootLoader: "grub"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: ""
efiBootMgr: "efibootmgr"
efiBootloaderId: "matcha"
installEFIFallback: true
