dontChroot: false
timeout: 600
script:
    - rm -f /etc/apk/matcha-pkgs
    - rm -rf /var/cache/apk/*

dontChroot: true
timeout: 600
script:
    - umount -l ${ROOT}/media/cdrom || true
    - umount -l ${ROOT}/etc/calamares/excludes || true
    - umount -l ${ROOT}/etc/calamares/scripts || true
    - rm -rf ${ROOT}/etc/calamares
    - rm -rf ${ROOT}/media/cdrom
