dontChroot: false
timeout: 600
script:
    - apk add --no-cache $(ls /media/cdrom/apks/$(uname -m)/*.apk | grep -vEf /etc/calamares/excludes/packages.txt)
    - >
      echo 'GRUB_TIMEOUT=3
      GRUB_DISTRIBUTOR="Matcha Linux"
      GRUB_DEFAULT=0
      GRUB_DISABLE_LINUX_UUID=false
      GRUB_ENABLE_CRYPTODISK=y
      GRUB_CMDLINE_LINUX_DEFAULT="quiet cryptroot=UUID=TARGET_UUID cryptdm=root modules=ext4"' > /etc/default/grub
    - /etc/calamares/scripts/luks.sh
    - echo 'features="ata base cdrom ext4 keymap kms mmc nvme raid scsi usb virtio cryptsetup lvm"' > /etc/mkinitfs/mkinitfs.conf
