defaultGroups:
    - name: users
      must_exist: false
      system: true
    - name: wheel
      must_exist: false
      system: true
    - audio
    - video
    - input
    - netdev
    - autologin
    - name: nopasswdlogin
      must_exist: false
      system: true

sudoersGroup: wheel
sudoersConfigureWithGroup: false

autologinGroup: autologin
displayAutologin: false
doAutologin: false

setRootPassword: true
doReusePassword: false

user:
    shell: /bin/zsh
    forbidden_names: [ root ]
    home_permissions: "o750"

hostname:
    location: EtcFile
    writeHostsFile: true
    template: "matcha-${product}"
    forbidden_names: [ localhost ]

allowActiveDirectory: false

presets:
    fullName:
        editable: true
    loginName:
        editable: true
