name: Build Matcha Calamares APK

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: alpine:3.23
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Build Script
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload APK Artifact (Local Builds Only)
        if: ${{ env.ACT == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: matcha-calamares-apk
          path: |
            /out/**/*.apk
            /out/*.rsa.pub
          if-no-files-found: error

      - name: Upload APK to Release
        if: ${{ env.ACT != 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            /out/**/*.apk
            /out/*.rsa.pub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
